/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string, 'slug' : string }
export interface Collection {
  'id' : bigint,
  'productIds' : Array<ProductId>,
  'name' : string,
  'description' : string,
}
export type MediaUrl = string;
export interface Order {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'city' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
  'email' : string,
  'orderId' : string,
  'state' : string,
  'totalAmount' : Price,
  'items' : Array<OrderItem>,
  'fullAddress' : string,
  'pincode' : string,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : Price,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'UPI' : null } |
  { 'Card' : null };
export type Price = number;
export interface Product {
  'id' : ProductId,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : MediaUrl,
  'price' : Price,
}
export type ProductId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], Category>,
  'addCollection' : ActorMethod<[string, string], Collection>,
  'addProduct' : ActorMethod<
    [string, Price, MediaUrl, string, string, bigint],
    Product
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignProductToCollection' : ActorMethod<[bigint, ProductId], undefined>,
  'claimAdmin' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      PaymentMethod,
      Array<OrderItem>,
      Price,
    ],
    Order
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteCollection' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'fetchProduct' : ActorMethod<[ProductId], Product>,
  'filterByCategory' : ActorMethod<[string], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllCollections' : ActorMethod<[], Array<Collection>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionById' : ActorMethod<[bigint], [] | [Collection]>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeProductFromCollection' : ActorMethod<[bigint, ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, string], Category>,
  'updateCollection' : ActorMethod<[bigint, string, string], Collection>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], Order>,
  'updateProduct' : ActorMethod<
    [ProductId, string, Price, MediaUrl, string, string, bigint],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];