/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Collection = IDL.Record({
  'id' : IDL.Nat,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Price = IDL.Float64;
export const MediaUrl = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : MediaUrl,
  'price' : Price,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : Price,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'state' : IDL.Text,
  'totalAmount' : Price,
  'items' : IDL.Vec(OrderItem),
  'fullAddress' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
  'addCollection' : IDL.Func([IDL.Text, IDL.Text], [Collection], []),
  'addProduct' : IDL.Func(
      [IDL.Text, Price, MediaUrl, IDL.Text, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignProductToCollection' : IDL.Func([IDL.Nat, ProductId], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PaymentMethod,
        IDL.Vec(OrderItem),
        Price,
      ],
      [Order],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteCollection' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'fetchProduct' : IDL.Func([ProductId], [Product], ['query']),
  'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectionById' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeProductFromCollection' : IDL.Func([IDL.Nat, ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Category], []),
  'updateCollection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [Collection],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [Order], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, Price, MediaUrl, IDL.Text, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Collection = IDL.Record({
    'id' : IDL.Nat,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Price = IDL.Float64;
  const MediaUrl = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : MediaUrl,
    'price' : Price,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'COD' : IDL.Null,
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : Price,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'orderStatus' : OrderStatus,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'state' : IDL.Text,
    'totalAmount' : Price,
    'items' : IDL.Vec(OrderItem),
    'fullAddress' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
    'addCollection' : IDL.Func([IDL.Text, IDL.Text], [Collection], []),
    'addProduct' : IDL.Func(
        [IDL.Text, Price, MediaUrl, IDL.Text, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignProductToCollection' : IDL.Func([IDL.Nat, ProductId], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PaymentMethod,
          IDL.Vec(OrderItem),
          Price,
        ],
        [Order],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteCollection' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'fetchProduct' : IDL.Func([ProductId], [Product], ['query']),
    'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectionById' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeProductFromCollection' : IDL.Func([IDL.Nat, ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Category], []),
    'updateCollection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [Collection],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [Order], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, Price, MediaUrl, IDL.Text, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };